export type StorageErrorCode =
// table part error codes
  | "TABLE_NOT_FOUND" //表不存在
  | "TABLE_CREATE_FAILED" //表创建失败
  | "TABLE_DELETE_FAILED" //表删除失败
  | "TABLE_UPDATE_FAILED" //表更新失败
  | "TABLE_READ_FAILED" //表读取失败
  | "TABLE_COUNT_FAILED" //表计数失败
  | "TABLE_SIZE_FAILED" //表大小失败
  | "TABLE_CHUNK_FAILED" //表分片失败
  | "TABLE_CHUNK_SIZE_FAILED" //表分片大小失败
  | "TABLE_CHUNK_SIZE_TOO_SMALL" //表分片大小太小
  | "TABLE_CHUNK_SIZE_TOO_LARGE" //表分片大小太大
  | "TABLE_CHUNK_SIZE_TOO_MANY" //表分片大小太多
  | "TABLE_CHUNK_SIZE_TOO_FEW" //表分片大小太少
  | "TABLE_CHUNK_SIZE_TOO_MUCH" //表分片大小太多
  | "TABLE_CHUNK_SIZE_TOO_LITTLE" //表分片大小太少
  | "TABLE_ALREADY_EXISTS" //表已存在
  | "TABLE_NAME_INVALID" //表名无效
  | "TABLE_COLUMN_INVALID" //表列无效 
  | "TABLE_INDEX_INVALID" //表索引无效
  | "TABLE_INDEX_ALREADY_EXISTS" //表索引已存在
  | "TABLE_INDEX_NOT_FOUND" //表索引不存在
  | "TABLE_INDEX_NAME_INVALID" //表索引名无效
  | "TABLE_INDEX_TYPE_INVALID" //表索引类型无效
  | "TABLE_INDEX_UNIQUE_INVALID" //表索引唯一性无效
  | "TABLE_INDEX_NOT_UNIQUE" //表索引不唯一
  | "TABLE_INDEX_NOT_UNIQUE" //表索引不唯一
// file part error codes
  | "FILE_NOT_FOUND" //文件不存在
  | "FILE_ALREADY_EXISTS" //文件已存在
  | "FILE_NAME_INVALID" //文件名无效
  | "FILE_CONTENT_INVALID" //文件内容无效
  | "FILE_CONTENT_TOO_LARGE" //文件内容太大
  | "FILE_CONTENT_TOO_SMALL" //文件内容太小
  | "FILE_CONTENT_TOO_LONG" //文件内容太长
  | "FILE_CONTENT_TOO_SHORT" //文件内容太短
  | "FILE_CONTENT_TOO_MANY" //文件内容太多
  | "FILE_CONTENT_TOO_FEW" //文件内容太少
  | "FILE_READ_FAILED" //文件读取失败
  | "FILE_WRITE_FAILED" //文件写入失败
  | "FILE_DELETE_FAILED" //文件删除失败
  | "FILE_MOVE_FAILED" //文件移动失败
  | "FILE_COPY_FAILED" //文件复制失败
  | "FILE_RENAME_FAILED" //文件重命名失败
  | "FILE_TRUNCATE_FAILED" //文件截断失败
  | "FILE_CLOSE_FAILED" //文件关闭失败
  | "FILE_SEEK_FAILED" //文件定位失败
  | "FILE_TELL_FAILED" //文件长度失败
// other part error codes
  | "UNKNOWN" //未知错误
  | "TIMEOUT" //超时
  | "PERMISSION_DENIED" //权限不足
  | "DISK_FULL" //磁盘满
  | "CORRUPTED_DATA" //数据损坏
  | "DATA_INCOMPLETE" //数据不完整
  | "CHUNK_INTEGRITY_FAILED" //分片完整性失败
  | "META_FILE_READ_ERROR" //元文件读取失败
  | "META_FILE_WRITE_ERROR" //元文件写入失败
  ;